blank_issues_enabled: false
contact_links:
  - name: Mautic Community Documentation
    url: https://contribute.mautic.org/
    about: Please check our documentation before creating an onboarding request.