blank_issues_enabled: false
contact_links:
  - name: Mautic Community Documentation
    url: https://mau.tc/contribute
    about: Please check our documentation before creating an onboarding request.

templates:
  - name: Community Team Onboarding
    about: Request to join the Mautic Community Team
    filename: 1-community-team-onboarding.yml
  - name: MautiCon Working Group Onboarding
    about: Request to join the MautiCon Working Group
    filename: 2-mauticon-onboarding.yml
  - name: Product Team - Tester
    about: Join the product team as a PR/release tester
    filename: 10-product-tester-onboarding.yml
  - name: Product Team - Triage
    about: Join the team that helps triage issues and PRs
    filename: 11-product-triage-onboarding.yml
  - name: Marketing Team - Content Writer
    about: 7-Contribute as a content writer for Mautic marketing
    filename: marketing-content-onboarding.yml
  - name: Marketing Team - Designer
    about: 8-Join as a designer for Mautic marketing materials
    filename: marketing-designer-onboarding.yml
  - name: Marketing Team - Website
    about: Contribute to the Mautic website
    filename: 9-marketing-website-onboarding.yml
  - name: Education - User Documentation
    about: Help create and maintain user documentation
    filename: 3-education-user-docs-onboarding.yml
  - name: Education - Developer Documentation
    about: Contribute to developer documentation
    filename: 4-education-dev-docs-onboarding.yml
  - name: Education - Knowledgebase
    about: Write knowledgebase articles
    filename: 5-education-kb-onboarding.yml
  - name: Forums Moderator
    about: Become a moderator for Mautic forums
    filename: 6-forums-moderator-onboarding.yml
  - name: Council Member
    about: Onboarding for newly elected council members
    filename: 14-council-member-onboarding.yml
  - name: Security Team
    about: Join the Mautic security team
    filename: 12-security-team-onboarding.yml
  - name: Core Team Member
    about: Become a Mautic core team member
    filename: 13-core-team-onboarding.yml
