name: Community Team Onboarding
description: Request to join the Mautic Community Team
title: "[Community] Onboarding request for: "
labels: ["onboarding", "community-team"]

body:
  - type: markdown
    attributes:
      value: |
        # Community Team Onboarding
        
        Thank you for your interest in joining the Mautic Community Team! This form will help us understand your interests and guide you through the onboarding process.
        
  - type: input
    id: name
    attributes:
      label: Full Name
      description: Your full name as you'd like it to appear in community materials
      placeholder: Aisha Chowdhury
    validations:
      required: true
     
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Your preferred email for community communications, please write in the format aisha[@]example[.]com
      placeholder: aisha[@]example[.]com
    validations:
      required: true
      